name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "main", "develop" ]
  pull_request:
<<<<<<< HEAD
    branches: [ "master", "main" ]
=======
    branches: [ "main", "master" ]
>>>>>>> 6383239 (zamena mastera)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test Users Service
      run: |
        cd users-service
        go mod tidy
        # Для users-service пока нет тестов, но проверим сборку
        go build -v .

    - name: Start Users Service
      run: |
        cd users-service
        nohup go run main.go > users.log 2>&1 &
        sleep 3
        echo "Users service started"
        cat users.log

    - name: Test Orders Service Integration
      run: |
        cd orders-service
        go mod tidy
        # Запустим интеграционные тесты
        go test -v -timeout 30s ./...

    - name: Build Orders Service
      run: |
        cd orders-service
        go build -v .

    - name: Test End-to-End API (optional)
      run: |
        # Запустим orders-service и протестируем API
        cd orders-service
        nohup go run main.go > orders.log 2>&1 &
        sleep 3
        
        # Проверим health checks
        curl -f http://localhost:8081/health
        curl -f http://localhost:8082/health
        
        # Создадим тестовый заказ
        response=$(curl -s -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -d '{"user_id":1,"product":"CI Test","quantity":1,"status":"pending"}' \
          http://localhost:8082/orders)
        
        http_code="${response: -3}"
        if [ "$http_code" != "200" ] && [ "$http_code" != "201" ]; then
          echo "E2E test failed! HTTP code: $http_code"
          echo "Response: ${response%???}"
          exit 1
        fi
        echo "E2E test passed!"

    - name: Upload test logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: service-logs
        path: |
          users-service/users.log
          orders-service/orders.log
